import { useEffect, useRef, useState } from "react";
import { useLanguage } from "../context/LanguageContext";
import { askChatbot, sendContactForm } from "../api/client";
import RobotAvatar from "./RobotAvatar";

const TOPICS = {
  fr: ["💶 Tarifs", "🦷 Quel traitement ?", "📎 Que dois-je envoyer ?", "😣 Douleur / urgence", "🩹 Après un soin", "✈️ Voyage", "🦷 Implants", "🗣️ Parler à un humain"],
  en: ["💶 Pricing", "🦷 Which treatment?", "📎 What should I send?", "😣 Pain / urgent", "🩹 Aftercare", "✈️ Travel", "🦷 Implants", "🗣️ Talk to a human"],
  it: ["💶 Prezzi", "🦷 Quale trattamento?", "📎 Cosa inviare?", "😣 Dolore / urgenza", "🩹 Dopo il trattamento", "✈️ Viaggio", "🦷 Impianti", "🗣️ Parla con una persona"],
  es: ["💶 Precios", "🦷 ¿Qué tratamiento?", "📎 ¿Qué debo enviar?", "😣 Dolor / urgencia", "🩹 Después del tratamiento", "✈️ Viaje", "🦷 Implantes", "🗣️ Hablar con una persona"],
  de: ["💶 Preise", "🦷 Welche Behandlung?", "📎 Was soll ich senden?", "😣 Schmerz / Notfall", "🩹 Nachsorge", "✈️ Reise", "🦷 Implantate", "🗣️ Mit einem Menschen sprechen"],
  pt: ["💶 Preços", "🦷 Qual tratamento?", "📎 O que devo enviar?", "😣 Dor / urgência", "🩹 Pós-tratamento", "✈️ Viagem", "🦷 Implantes", "🗣️ Falar com uma pessoa"],
  ru: ["💶 Цены", "🦷 Какое лечение?", "📎 Что отправить?", "😣 Боль / срочно", "🩹 После лечения", "✈️ Поездка", "🦷 Импланты", "🗣️ Поговорить с человеком"],
  ar: ["💶 الأسعار", "🦷 أي علاج؟", "📎 ماذا أرسل؟", "😣 ألم / طوارئ", "🩹 بعد العلاج", "✈️ السفر", "🦷 الزرعات", "🗣️ التحدث مع شخص"],
  sq: ["💶 Çmimet", "🦷 Cili trajtim?", "📎 Çfarë të dërgoj?", "😣 Dhimbje / urgjencë", "🩹 Pas trajtimit", "✈️ Udhëtimi", "🦷 Implantet", "🗣️ Fol me një person"],
  zh: ["💶 价格", "🦷 哪种治疗？", "📎 需要发送什么？", "😣 牙痛 / 紧急", "🩹 治疗后", "✈️ 旅行", "🦷 种植牙", "🗣️ 联系人工"]
};
const UI = {
  fr: { common:"Questions fréquentes", send:"Envoyer", human:"Parler à un humain", formTitle:"Votre demande à l’équipe Virtus", formIntro:"Laissez vos coordonnées. L’équipe vous répondra directement.", name:"Nom complet", country:"Pays", email:"Email", phone:"Téléphone / WhatsApp", message:"Décrivez votre besoin", channel:"Je préfère être contacté par", emailChannel:"Email", phoneChannel:"Téléphone", whatsappChannel:"WhatsApp", consent:"J’accepte que Virtus utilise ces informations pour me recontacter au sujet de ma demande.", submit:"Envoyer ma demande", cancel:"Retour au chat", sent:"Demande transmise", error:"La demande n’a pas pu être transmise.", backend:"Le serveur Virtus ne répond pas. Vérifiez que le backend est lancé sur le port 4000.", retry:"Réessayer", required:"Veuillez remplir les champs obligatoires.", welcome:"Choisissez un sujet ou décrivez simplement votre projet. Pour une demande personnalisée, je peux vous mettre en relation avec l’équipe.", transmitting:"Transmission…", close:"Fermer", open:"Ouvrir l’assistant" },
  en: { common:"Common questions", send:"Send", human:"Talk to a human", formTitle:"Your request to the Virtus team", formIntro:"Leave your details and the team will reply directly.", name:"Full name", country:"Country", email:"Email", phone:"Phone / WhatsApp", message:"Tell us what you need", channel:"Preferred contact method", emailChannel:"Email", phoneChannel:"Phone", whatsappChannel:"WhatsApp", consent:"I agree that Virtus may use this information to contact me about my request.", submit:"Send my request", cancel:"Back to chat", sent:"Request sent", error:"The request could not be sent.", backend:"The Virtus server is not responding. Check that the backend is running on port 4000.", retry:"Try again", required:"Please complete the required fields.", welcome:"Choose a topic or simply describe your project. For a personalized request, I can connect you with the team.", transmitting:"Sending…", close:"Close", open:"Open assistant" },
  it: { common:"Domande frequenti", send:"Invia", human:"Parla con una persona", formTitle:"La tua richiesta al team Virtus", formIntro:"Lascia i tuoi dati e il team ti risponderà direttamente.", name:"Nome e cognome", country:"Paese", email:"Email", phone:"Telefono / WhatsApp", message:"Descrivi la tua esigenza", channel:"Preferisco essere contattato tramite", emailChannel:"Email", phoneChannel:"Telefono", whatsappChannel:"WhatsApp", consent:"Accetto che Virtus utilizzi queste informazioni per ricontattarmi in merito alla mia richiesta.", submit:"Invia la richiesta", cancel:"Torna alla chat", sent:"Richiesta inviata", error:"Impossibile inviare la richiesta.", backend:"Il server Virtus non risponde. Verifica che il backend sia avviato sulla porta 4000.", retry:"Riprova", required:"Compila i campi obbligatori.", welcome:"Scegli un argomento o descrivi semplicemente il tuo progetto. Per una richiesta personalizzata posso metterti in contatto con il team.", transmitting:"Invio…", close:"Chiudi", open:"Apri assistente" },
  es: { common:"Preguntas frecuentes", send:"Enviar", human:"Hablar con una persona", formTitle:"Tu solicitud al equipo Virtus", formIntro:"Déjanos tus datos y el equipo te responderá directamente.", name:"Nombre completo", country:"País", email:"Email", phone:"Teléfono / WhatsApp", message:"Describe tu necesidad", channel:"Prefiero ser contactado por", emailChannel:"Email", phoneChannel:"Teléfono", whatsappChannel:"WhatsApp", consent:"Acepto que Virtus utilice estos datos para contactarme sobre mi solicitud.", submit:"Enviar mi solicitud", cancel:"Volver al chat", sent:"Solicitud enviada", error:"No se ha podido enviar la solicitud.", backend:"El servidor de Virtus no responde. Comprueba que el backend esté activo en el puerto 4000.", retry:"Reintentar", required:"Completa los campos obligatorios.", welcome:"Elige un tema o describe tu proyecto. Para una solicitud personalizada, puedo ponerte en contacto con el equipo.", transmitting:"Enviando…", close:"Cerrar", open:"Abrir asistente" },
  de: { common:"Häufige Fragen", send:"Senden", human:"Mit einem Menschen sprechen", formTitle:"Ihre Anfrage an das Virtus-Team", formIntro:"Hinterlassen Sie Ihre Kontaktdaten. Das Team antwortet direkt.", name:"Vollständiger Name", country:"Land", email:"E-Mail", phone:"Telefon / WhatsApp", message:"Beschreiben Sie Ihr Anliegen", channel:"Bevorzugte Kontaktart", emailChannel:"E-Mail", phoneChannel:"Telefon", whatsappChannel:"WhatsApp", consent:"Ich stimme zu, dass Virtus diese Angaben zur Kontaktaufnahme bezüglich meiner Anfrage verwendet.", submit:"Anfrage senden", cancel:"Zurück zum Chat", sent:"Anfrage gesendet", error:"Die Anfrage konnte nicht gesendet werden.", backend:"Der Virtus-Server antwortet nicht. Prüfen Sie, ob das Backend auf Port 4000 läuft.", retry:"Erneut versuchen", required:"Bitte füllen Sie die Pflichtfelder aus.", welcome:"Wählen Sie ein Thema oder beschreiben Sie Ihr Vorhaben. Für eine persönliche Anfrage kann ich Sie mit dem Team verbinden.", transmitting:"Wird gesendet…", close:"Schließen", open:"Assistent öffnen" },
  pt: { common:"Perguntas frequentes", send:"Enviar", human:"Falar com uma pessoa", formTitle:"O seu pedido à equipa Virtus", formIntro:"Deixe os seus dados e a equipa responderá diretamente.", name:"Nome completo", country:"País", email:"Email", phone:"Telefone / WhatsApp", message:"Descreva a sua necessidade", channel:"Prefiro ser contactado por", emailChannel:"Email", phoneChannel:"Telefone", whatsappChannel:"WhatsApp", consent:"Aceito que a Virtus utilize estes dados para me contactar sobre o meu pedido.", submit:"Enviar pedido", cancel:"Voltar ao chat", sent:"Pedido enviado", error:"Não foi possível enviar o pedido.", backend:"O servidor Virtus não responde. Verifique se o backend está ativo na porta 4000.", retry:"Tentar novamente", required:"Preencha os campos obrigatórios.", welcome:"Escolha um tema ou descreva o seu projeto. Para um pedido personalizado, posso colocá-lo em contacto com a equipa.", transmitting:"A enviar…", close:"Fechar", open:"Abrir assistente" },
  ru: { common:"Частые вопросы", send:"Отправить", human:"Поговорить с человеком", formTitle:"Ваш запрос команде Virtus", formIntro:"Оставьте контакты, и команда ответит напрямую.", name:"Имя и фамилия", country:"Страна", email:"Email", phone:"Телефон / WhatsApp", message:"Опишите вашу ситуацию", channel:"Предпочтительный способ связи", emailChannel:"Email", phoneChannel:"Телефон", whatsappChannel:"WhatsApp", consent:"Я согласен на использование этих данных для связи со мной по поводу запроса.", submit:"Отправить запрос", cancel:"Вернуться в чат", sent:"Запрос отправлен", error:"Не удалось отправить запрос.", backend:"Сервер Virtus не отвечает. Проверьте, запущен ли backend на порту 4000.", retry:"Повторить", required:"Заполните обязательные поля.", welcome:"Выберите тему или опишите вашу ситуацию. Для персонального запроса я могу связать вас с командой.", transmitting:"Отправка…", close:"Закрыть", open:"Открыть помощника" },
  ar: { common:"الأسئلة الشائعة", send:"إرسال", human:"التحدث مع شخص", formTitle:"طلبك إلى فريق Virtus", formIntro:"اترك بياناتك وسيرد عليك الفريق مباشرة.", name:"الاسم الكامل", country:"البلد", email:"البريد الإلكتروني", phone:"الهاتف / واتساب", message:"صف احتياجك", channel:"أفضل وسيلة للتواصل", emailChannel:"البريد الإلكتروني", phoneChannel:"الهاتف", whatsappChannel:"واتساب", consent:"أوافق على استخدام Virtus لهذه المعلومات للتواصل معي بشأن طلبي.", submit:"إرسال الطلب", cancel:"العودة إلى المحادثة", sent:"تم إرسال الطلب", error:"تعذر إرسال الطلب.", backend:"خادم Virtus لا يستجيب. تحقق من تشغيل الخادم الخلفي على المنفذ 4000.", retry:"إعادة المحاولة", required:"يرجى إكمال الحقول المطلوبة.", welcome:"اختر موضوعًا أو صف مشروعك ببساطة. لطلب مخصص، يمكنني ربطك بفريقنا.", transmitting:"جارٍ الإرسال…", close:"إغلاق", open:"فتح المساعد" },
  sq: { common:"Pyetje të shpeshta", send:"Dërgo", human:"Fol me një person", formTitle:"Kërkesa juaj për ekipin Virtus", formIntro:"Lini të dhënat dhe ekipi do t'ju përgjigjet drejtpërdrejt.", name:"Emri i plotë", country:"Shteti", email:"Email", phone:"Telefon / WhatsApp", message:"Përshkruani nevojën", channel:"Mënyra e preferuar e kontaktit", emailChannel:"Email", phoneChannel:"Telefon", whatsappChannel:"WhatsApp", consent:"Pranoj që Virtus t'i përdorë këto të dhëna për të më kontaktuar për kërkesën time.", submit:"Dërgo kërkesën", cancel:"Kthehu te biseda", sent:"Kërkesa u dërgua", error:"Kërkesa nuk u dërgua.", backend:"Serveri Virtus nuk përgjigjet. Kontrolloni nëse backend-i po punon në portën 4000.", retry:"Provo përsëri", required:"Plotësoni fushat e detyrueshme.", welcome:"Zgjidhni një temë ose përshkruani projektin tuaj. Për një kërkesë të personalizuar mund t'ju lidh me ekipin.", transmitting:"Duke dërguar…", close:"Mbyll", open:"Hap asistentin" },
  zh: { common:"常见问题", send:"发送", human:"联系人工", formTitle:"发送给 Virtus 团队的请求", formIntro:"留下您的联系方式，团队会直接回复您。", name:"姓名", country:"国家/地区", email:"邮箱", phone:"电话 / WhatsApp", message:"请描述您的需求", channel:"首选联系方式", emailChannel:"邮箱", phoneChannel:"电话", whatsappChannel:"WhatsApp", consent:"我同意 Virtus 使用这些信息就我的请求与我联系。", submit:"发送请求", cancel:"返回聊天", sent:"请求已发送", error:"请求无法发送。", backend:"Virtus 服务器没有响应。请确认后端运行在 4000 端口。", retry:"重试", required:"请填写必填字段。", welcome:"选择一个主题或直接描述您的需求。如需个性化请求，我可以为您联系团队。", transmitting:"正在发送…", close:"关闭", open:"打开助手" }
};
const DISCLAIMER={fr:"Informations générales uniquement · pas de diagnostic",en:"General information only · not a diagnosis",it:"Informazioni generali · non è una diagnosi",es:"Información general · no es un diagnóstico",de:"Allgemeine Informationen · keine Diagnose",pt:"Informação geral · não é diagnóstico",ru:"Общая информация · не диагноз",ar:"معلومات عامة فقط · ليست تشخيصًا",sq:"Informacion i përgjithshëm · jo diagnozë",zh:"仅供一般参考 · 不能替代诊断"};

export default function Chatbot({ open, onToggle }) {
  const { content, lang } = useLanguage();
  const [messages,setMessages]=useState([]), [input,setInput]=useState(""), [thinking,setThinking]=useState(false), [started,setStarted]=useState(false), [handoffOpen,setHandoffOpen]=useState(false);
  const [handoff,setHandoff]=useState({name:"",country:"",email:"",phone:"",message:"",consent:false,preferredChannel:"email"});
  const [handoffState,setHandoffState]=useState("idle");
  const bodyRef=useRef(null);
  const chat=content?.chat; const ui=UI[lang]||UI.en;
  useEffect(()=>{if(content&&!messages.length)setMessages([{who:"bot",text:chat.greeting}])},[content,chat?.greeting,messages.length]);
  useEffect(()=>{if(bodyRef.current)bodyRef.current.scrollTop=bodyRef.current.scrollHeight},[messages,thinking,handoffOpen,handoffState]);
  if(!content||!chat)return null;
  const handleReply=async(userText)=>{setStarted(true);setMessages(p=>[...p,{who:"user",text:userText}]);setThinking(true);try{const r=await askChatbot(userText,lang);setMessages(p=>[...p,{who:"bot",text:r.reply,handoff:r.handoff}]);if(r.handoff)setHandoffOpen(true)}catch{setMessages(p=>[...p,{who:"bot",text:chat.fallback,handoff:true}]);setHandoffOpen(true)}finally{setThinking(false)}};
  const send=()=>{const v=input.trim();if(!v)return;setInput("");handleReply(v)};
  const openHuman=()=>{setStarted(true);setHandoffOpen(true);setHandoffState("idle")};
  const update=(key,value)=>setHandoff(p=>({...p,[key]:value}));
  const submitHandoff=async(e)=>{e.preventDefault();if(!handoff.name||!handoff.country||!handoff.email||!handoff.message||!handoff.consent){setHandoffState("validation");return}setHandoffState("sending");try{await sendContactForm({name:handoff.name,country:handoff.country,email:handoff.email,phone:handoff.phone,treatment:"Demande via assistant Virtus",message:handoff.message,lang,preferredDate:"",preferredChannel:handoff.preferredChannel,consent:true,formLoadedAt:Date.now()-5000});setHandoffState("sent");setMessages(p=>[...p,{who:"bot",text:ui.sent}])}catch(error){const raw=String(error?.message||"");setHandoffState(/Failed to fetch|Network|fetch/i.test(raw)?"offline":"error")}};
  return <>
    <button className={`chat-fab${open ? " is-open" : ""}`} onClick={onToggle} aria-label={open ? ui.close : ui.open}><RobotAvatar/></button>
    <div className={`chat-panel${open?" open":""}`} aria-hidden={!open}>
      <div className="chat-head"><div className="chat-agent"><RobotAvatar small/><div><div className="t">{chat.title}</div><div className="s">{chat.subtitle}</div></div></div><button onClick={onToggle} aria-label={ui.close}>×</button></div>
      <div className="chat-body" ref={bodyRef}>
        {!started&&<div className="chat-welcome"><span className="chat-kicker">VIRTUS · ASSISTANT</span><div className="chat-welcome-title">{chat.greeting}</div><p>{ui.welcome}</p></div>}
        {messages.map((m,i)=><div key={i} className={`msg ${m.who}`}><div>{m.text}</div>{m.handoff&&!handoffOpen&&<button type="button" className="chat-human-btn" onClick={openHuman}>{ui.human} →</button>}</div>)}
        {thinking&&<div className="msg bot typing"><span></span><span></span><span></span></div>}
        {handoffOpen&&handoffState!=="sent"&&<form className="chat-handoff" onSubmit={submitHandoff}>
          <div className="handoff-heading"><span className="handoff-icon">↗</span><div><strong>{ui.formTitle}</strong><small>{ui.formIntro}</small></div></div>
          <div className="handoff-grid"><input required placeholder={ui.name} value={handoff.name} onChange={e=>update("name",e.target.value)}/><input required placeholder={ui.country} value={handoff.country} onChange={e=>update("country",e.target.value)}/><input required type="email" placeholder={ui.email} value={handoff.email} onChange={e=>update("email",e.target.value)}/><input placeholder={ui.phone} value={handoff.phone} onChange={e=>update("phone",e.target.value)}/></div>
          <textarea required rows="3" placeholder={ui.message} value={handoff.message} onChange={e=>update("message",e.target.value)}/>
          <div className="handoff-channel"><span>{ui.channel}</span><div>{[["email",ui.emailChannel],["phone",ui.phoneChannel],["whatsapp",ui.whatsappChannel]].map(([value,label])=><button key={value} type="button" className={handoff.preferredChannel===value?"active":""} onClick={()=>update("preferredChannel",value)}>{label}</button>)}</div></div>
          <label className="handoff-consent"><input type="checkbox" checked={handoff.consent} onChange={e=>update("consent",e.target.checked)}/><span>{ui.consent}</span></label>
          <div className="handoff-actions"><button className="handoff-submit" disabled={!handoff.consent||handoffState==="sending"} type="submit">{handoffState==="sending"?ui.transmitting:ui.submit}</button><button type="button" className="chat-cancel" onClick={()=>setHandoffOpen(false)}>{ui.cancel}</button></div>
          {handoffState==="validation"&&<small className="handoff-error">{ui.required}</small>}
          {handoffState==="offline"&&<div className="handoff-error"><strong>{ui.error}</strong><span>{ui.backend}</span><button type="button" onClick={()=>setHandoffState("idle")}>{ui.retry}</button></div>}
          {handoffState==="error"&&<div className="handoff-error"><strong>{ui.error}</strong><span>Le serveur a refusé ou n’a pas pu traiter la demande. Vérifiez le terminal du backend pour le détail.</span><button type="button" onClick={()=>setHandoffState("idle")}>{ui.retry}</button></div>}
        </form>}
      </div>
      <div className="chat-topic-label">{ui.common}</div><div className="quick-replies">{(TOPICS[lang]||TOPICS.en).map((label,i)=><button key={i} className="qr-btn" onClick={()=>i===7?openHuman():handleReply(label)}>{label}</button>)}</div>
      <button type="button" className="chat-human-bar" onClick={openHuman}><span>●</span> {ui.human}</button>
      <div className="chat-disclaimer">{DISCLAIMER[lang]||DISCLAIMER.en}</div><div className="chat-inputrow"><input type="text" placeholder={chat.placeholder} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()}/><button onClick={send} aria-label={ui.send}>↗</button></div>
    </div>
  </>;
}
