import { Link } from "react-router-dom";
import { useLanguage } from "../context/LanguageContext";
import { useReveal } from "../hooks/useReveal";
const DATA={
 fr:[["Implants dentaires : les étapes","De la première évaluation à la couronne définitive, comprendre les étapes qui peuvent être proposées."],["All-on-4 ou All-on-6 ?","Comprendre la différence entre les protocoles sans choisir un traitement avant l’évaluation clinique."],["Combien de jours à Tirana ?","Pourquoi la durée dépend du geste, de la cicatrisation et des contrôles nécessaires."],["Préparer ses photos dentaires","Comment prendre des photos nettes et utiles pour une première orientation à distance."],["Que demander dans un devis ?","Les éléments à vérifier : actes, matériaux, provisoires, contrôles et modalités de suivi."],["Après une extraction","Conseils généraux de soins et signes pour lesquels demander rapidement un avis professionnel."],["Douleur dentaire : que faire ?","Mesures générales et situations qui justifient une consultation rapide."],["Voyager après une chirurgie dentaire","Pourquoi le calendrier de voyage doit être confirmé avec l’équipe soignante."],["Facettes dentaires : à qui s’adressent-elles ?","Ce qu’une consultation doit évaluer avant toute décision esthétique."],["Greffe osseuse et sinus lift","Pourquoi ces interventions peuvent être proposées dans certains projets implantaires."],["Hygiène autour d’un implant","Principes généraux de nettoyage et importance des contrôles professionnels."],["Checklist du patient international","Les documents, questions et informations à préparer avant de réserver un séjour."]],
 en:[["Dental implants: the steps","From initial assessment to the final crown, understand the stages that may be proposed."],["All-on-4 or All-on-6?","Understand the difference without choosing a treatment before clinical assessment."],["How many days in Tirana?","Why timing depends on procedures, healing and required reviews."],["Preparing dental photos","How to take clear, useful photos for an initial remote orientation."],["What should a dental quote include?","Items to check: procedures, materials, provisionals, reviews and follow-up."],["After a tooth extraction","General aftercare principles and signs that need prompt professional advice."],["Dental pain: what to do","General measures and situations that call for prompt assessment."],["Flying after dental surgery","Why your travel schedule should be confirmed with the clinical team."],["Dental veneers: who are they for?","What an assessment should consider before an aesthetic decision."],["Bone grafting and sinus lift","Why these procedures may be considered in selected implant plans."],["Cleaning around an implant","General cleaning principles and the role of professional reviews."],["International patient checklist","Documents, questions and information to prepare before booking a trip."]]
};
const HEAD={fr:["BIBLIOTHÈQUE DENTAIRE","Des guides pour préparer une décision éclairée","Des informations générales pour comprendre les traitements et préparer votre séjour."],en:["DENTAL LIBRARY","Guides to help you prepare an informed decision","General information to help you understand treatments and prepare your trip."],it:["GUIDE DENTALI","Guide per preparare una decisione informata","Informazioni generali per comprendere i trattamenti e preparare il viaggio."],es:["GUÍAS DENTALES","Guías para preparar una decisión informada","Información general para comprender los tratamientos y preparar el viaje."],de:["ZAHNMEDIZINISCHE RATGEBER","Ratgeber für eine informierte Entscheidung","Allgemeine Informationen zu Behandlungen und Reisevorbereitung."],pt:["GUIAS DENTÁRIOS","Guias para preparar uma decisão informada","Informação geral para compreender tratamentos e preparar a viagem."],ru:["СТОМАТОЛОГИЧЕСКИЕ ГИДЫ","Гиды для осознанного решения","Общая информация о лечении и подготовке поездки."],ar:["أدلة طب الأسنان","أدلة تساعدك على اتخاذ قرار مستنير","معلومات عامة لفهم العلاجات والاستعداد للسفر."],sq:["UDHËZUES DENTARË","Udhëzues për një vendim të informuar","Informacion i përgjithshëm për trajtimet dhe përgatitjen e udhëtimit."],zh:["牙科指南","帮助您做出知情决定的指南","帮助了解治疗并准备牙科旅行的一般信息。"]};
export default function GuideLibrary(){const {lang}=useLanguage();const ref=useReveal();const items=DATA[lang]||DATA.en;const prefix=lang==="fr"?"":`/${lang}`;const h=HEAD[lang]||HEAD.en;return <section className="guide-library reveal" ref={ref}><div className="wrap"><div className="section-head"><span className="eyebrow">{h[0]}</span><h2>{h[1]}</h2><p>{h[2]} {lang==="fr"?"Elles ne remplacent pas une consultation clinique.":"They do not replace a clinical consultation."}</p></div><div className="guide-grid">{items.map(([t,d],i)=><article className="guide-card" key={t}><span>0{(i%12)+1}</span><h3>{t}</h3><p>{d}</p><Link to={`${prefix}/contact`}>{lang==="fr"?"Parler à l’équipe":"Talk to the team"} →</Link></article>)}</div></div></section>}
