import { Link } from "react-router-dom";
import { useLanguage } from "../context/LanguageContext";
import { useReveal } from "../hooks/useReveal";

const COPY = {
  fr: { eyebrow: "À EXPLORER", title: "Tout le reste, quand vous êtes prêt", intro: "La page d’accueil reste volontairement claire. Les informations détaillées sont accessibles en un clic, sans vous noyer dans une longue page.", cards: [["Tourisme dentaire","Préparez votre séjour, vos examens et les étapes avant de réserver.","dental-tourism","Voir le parcours"],["Avant / après","Explorez les cas, résultats et vidéos disponibles au centre.","before-after","Voir les cas"],["Visite virtuelle","Entrez dans la clinique avant votre arrivée à Tirana.","virtual-tour","Visiter la clinique"],["Guides dentaires","Conseils pour comprendre les traitements et préparer votre dossier.","blog","Lire les guides"]] },
  en: { eyebrow: "EXPLORE", title: "Everything else, when you are ready", intro: "The homepage stays intentionally clear. Detailed information is one click away, without turning the first visit into an endless scroll.", cards: [["Dental tourism","Prepare your stay, records and treatment steps before you book.","dental-tourism","Explore the journey"],["Before / after","Explore available cases, results and patient videos.","before-after","See the cases"],["Virtual tour","Step inside the clinic before you arrive in Tirana.","virtual-tour","Tour the clinic"],["Dental guides","Practical information to understand treatments and prepare your case.","blog","Read the guides"]] },
  it: { eyebrow: "DA ESPLORARE", title: "Tutto il resto, quando sei pronto", intro: "La homepage resta volutamente chiara. Le informazioni dettagliate sono a un clic di distanza.", cards: [["Turismo dentale","Prepara soggiorno, esami e fasi del trattamento.","dental-tourism","Scopri il percorso"],["Prima / dopo","Guarda casi, risultati e video disponibili.","before-after","Vedi i casi"],["Tour virtuale","Entra nella clinica prima di arrivare a Tirana.","virtual-tour","Visita la clinica"],["Guide dentali","Informazioni pratiche per capire i trattamenti.","blog","Leggi le guide"]] },
  es: { eyebrow: "PARA EXPLORAR", title: "Todo lo demás, cuando estés listo", intro: "La página de inicio se mantiene clara. La información detallada está a un clic.", cards: [["Turismo dental","Prepara tu estancia, pruebas y etapas del tratamiento.","dental-tourism","Ver el recorrido"],["Antes / después","Explora casos, resultados y vídeos disponibles.","before-after","Ver los casos"],["Visita virtual","Entra en la clínica antes de llegar a Tirana.","virtual-tour","Visitar la clínica"],["Guías dentales","Información práctica para comprender los tratamientos.","blog","Leer las guías"]] },
  de: { eyebrow: "ENTDECKEN", title: "Alles Weitere, wenn Sie bereit sind", intro: "Die Startseite bleibt bewusst übersichtlich. Detaillierte Informationen sind nur einen Klick entfernt.", cards: [["Zahntourismus","Planen Sie Aufenthalt, Unterlagen und Behandlungsschritte.","dental-tourism","Ablauf ansehen"],["Vorher / nachher","Entdecken Sie verfügbare Fälle, Ergebnisse und Videos.","before-after","Fälle ansehen"],["Virtueller Rundgang","Betreten Sie die Klinik vor Ihrer Ankunft in Tirana.","virtual-tour","Klinik besuchen"],["Dental-Ratgeber","Praktische Informationen zu Behandlungen und Vorbereitung.","blog","Ratgeber lesen"]] },
  pt: { eyebrow: "EXPLORAR", title: "O resto, quando estiver pronto", intro: "A página inicial permanece clara. As informações detalhadas ficam a um clique.", cards: [["Turismo dentário","Prepare estadia, exames e etapas do tratamento.","dental-tourism","Ver o percurso"],["Antes / depois","Explore casos, resultados e vídeos disponíveis.","before-after","Ver casos"],["Visita virtual","Entre na clínica antes de chegar a Tirana.","virtual-tour","Visitar a clínica"],["Guias dentários","Informação prática para compreender os tratamentos.","blog","Ler os guias"]] },
  ru: { eyebrow: "ИЗУЧИТЬ", title: "Остальное — когда будете готовы", intro: "Главная страница остаётся понятной. Подробная информация доступна в один клик.", cards: [["Стоматологический туризм","Подготовьте поездку, обследования и этапы лечения.","dental-tourism","Посмотреть путь"],["До / после","Изучите доступные случаи, результаты и видео.","before-after","Посмотреть случаи"],["Виртуальный тур","Посетите клинику до приезда в Тирану.","virtual-tour","Посетить клинику"],["Стоматологические гайды","Практическая информация о лечении и подготовке.","blog","Читать гайды"]] },
  ar: { eyebrow: "استكشف", title: "بقية المعلومات عندما تكون مستعدًا", intro: "الصفحة الرئيسية تبقى واضحة ومريحة. التفاصيل متاحة بنقرة واحدة.", cards: [["السياحة العلاجية للأسنان","حضّر رحلتك وفحوصاتك ومراحل العلاج.","dental-tourism","استكشف المسار"],["قبل / بعد","استعرض الحالات والنتائج ومقاطع الفيديو المتاحة.","before-after","شاهد الحالات"],["جولة افتراضية","ادخل إلى العيادة قبل وصولك إلى تيرانا.","virtual-tour","زر العيادة"],["أدلة الأسنان","معلومات عملية لفهم العلاجات والاستعداد.","blog","اقرأ الأدلة"]] },
  sq: { eyebrow: "EKSPLORE", title: "Gjithçka tjetër, kur të jeni gati", intro: "Faqja kryesore mbetet e qartë. Informacioni i detajuar është vetëm një klik larg.", cards: [["Turizëm dentar","Përgatitni udhëtimin, ekzaminimet dhe hapat e trajtimit.","dental-tourism","Shihni rrugëtimin"],["Para / pas","Eksploroni rastet, rezultatet dhe videot.","before-after","Shihni rastet"],["Tur virtual","Hyni në klinikë para se të mbërrini në Tiranë.","virtual-tour","Vizitoni klinikën"],["Udhëzues dentarë","Informacion praktik për trajtimet dhe përgatitjen.","blog","Lexoni udhëzuesit"]] },
  zh: { eyebrow: "探索更多", title: "准备好后，再了解更多", intro: "首页保持简洁清晰，详细内容只需一键进入，不必一次阅读很长的页面。", cards: [["牙科旅游","提前准备行程、检查资料和治疗步骤。","dental-tourism","查看治疗流程"],["治疗前后","浏览可公开展示的病例、结果和视频。","before-after","查看病例"],["虚拟参观","抵达地拉那前先在线参观诊所。","virtual-tour","参观诊所"],["牙科指南","了解治疗项目并准备您的病例资料。","blog","阅读指南"]] }
};

export default function HomeExplore() {
  const { lang } = useLanguage();
  const ref = useReveal();
  const d = COPY[lang] || COPY.en;
  const prefix = lang === "fr" ? "" : `/${lang}`;
  return <section className="home-explore reveal" ref={ref} id="explore"><div className="wrap"><div className="sec-head"><span className="eyebrow">{d.eyebrow}</span><h2>{d.title}</h2><p>{d.intro}</p></div><div className="explore-grid">{d.cards.map(([title,body,slug,cta],i)=><Link className="explore-card" key={slug} to={`${prefix}/${slug}`}><span className="explore-index">0{i+1}</span><h3>{title}</h3><p>{body}</p><span className="explore-link">{cta} <span aria-hidden="true">↗</span></span></Link>)}</div></div></section>;
}
