import { Link, useParams } from "react-router-dom";
import { useLanguage } from "../context/LanguageContext";
import SEOHead from "./SEOHead";
import Header from "./Header";
import Footer from "./Footer";

const BASE = {
  fr: {
    privacy: ["Politique de confidentialité", "Informations sur les données transmises via le site Virtus Dental Center.", [["Données envoyées volontairement", "Le formulaire reçoit les informations que vous choisissez de transmettre, comme votre nom, pays, email, téléphone, message et fichiers joints, afin de répondre à votre demande."], ["Données de santé", "N'envoyez que les informations nécessaires. Les photos, radiographies et documents médicaux peuvent contenir des données de santé sensibles et sont traités uniquement pour l'évaluation de votre demande."], ["Statistiques", "Google Analytics est désactivé par défaut et n'est chargé qu'après votre consentement. Vous pouvez continuer à utiliser le site sans statistiques."], ["Vos droits", "Pour demander l'accès, la rectification ou la suppression de vos informations, contactez virtusdentalpro@gmail.com."]]],
    cookies: ["Politique de cookies", "Le site privilégie une utilisation minimale des cookies et technologies de suivi.", [["Cookies nécessaires", "Ils permettent le fonctionnement technique du site, la navigation et certaines préférences. Ils ne servent pas à établir un profil publicitaire."], ["Statistiques facultatives", "Google Analytics n'est chargé qu'après votre accord. Votre choix est conservé localement dans votre navigateur."], ["Services externes", "Les cartes, visites virtuelles ou réseaux sociaux peuvent charger des contenus depuis des services tiers lorsque vous les ouvrez. Leurs propres règles s'appliquent."]]],
    legal: ["Mentions légales", "Informations générales concernant le site Virtus Dental Center.", [["Éditeur", "Virtus Dental Center, Rruga Teodor Keko, Pll 29, 1027 Tirana, Albanie. Email : virtusdentalpro@gmail.com. Téléphone : +33 6 28 27 01 18."], ["Nature des informations", "Les contenus sont informatifs. Ils ne constituent ni un diagnostic, ni une prescription, ni une garantie de résultat. Une indication thérapeutique doit être confirmée après examen clinique."], ["Droits sur les contenus", "Les textes, photos, vidéos, éléments graphiques et marques sont protégés par les droits applicables. Toute réutilisation non autorisée est interdite."], ["Urgence", "En cas de difficulté à respirer ou avaler, de gonflement important du visage ou du cou, ou de situation mettant votre sécurité en jeu, contactez immédiatement les services d'urgence locaux."]]]
  },
  en: {
    privacy: ["Privacy policy", "Information about data submitted through the Virtus Dental Center website.", [["Information you provide", "The contact form receives the information you choose to provide, such as your name, country, email, phone, message and attachments, so the team can answer your request."], ["Health information", "Send only information needed for your request. Photos, X-rays and medical documents may contain sensitive health data and are processed for assessment of your request."], ["Analytics", "Google Analytics is disabled by default and loaded only after your consent. You can continue using the website without analytics."], ["Your rights", "To request access, correction or deletion of your information, contact virtusdentalpro@gmail.com."]]],
    cookies: ["Cookie policy", "The website aims to use as few cookies and tracking technologies as possible.", [["Essential cookies", "They support technical operation, navigation and selected preferences. They are not used to build an advertising profile."], ["Optional analytics", "Google Analytics loads only after your consent. Your choice is stored locally in your browser."], ["External services", "Maps, virtual tours and social networks may load third-party content when opened. Those services have their own privacy rules."]]],
    legal: ["Legal notice", "General information about the Virtus Dental Center website.", [["Publisher", "Virtus Dental Center, Rruga Teodor Keko, Pll 29, 1027 Tirana, Albania. Email: virtusdentalpro@gmail.com. Phone: +33 6 28 27 01 18."], ["Nature of information", "Website content is informational. It is not a diagnosis, prescription or guarantee of outcome. Treatment indications must be confirmed after clinical examination."], ["Content rights", "Texts, photographs, videos, graphics and trademarks are protected by applicable rights. Unauthorised reuse is prohibited."], ["Emergency", "If you have difficulty breathing or swallowing, significant face or neck swelling, or another immediate safety concern, contact local emergency services immediately."]]]
  },
  it: {
    privacy: ["Privacy", "Informazioni sui dati inviati tramite il sito Virtus Dental Center.", [["Dati forniti", "Il modulo riceve solo le informazioni che scegli di inviare, come nome, paese, email, telefono, messaggio e allegati, per rispondere alla richiesta."], ["Dati sanitari", "Invia solo le informazioni necessarie. Foto, radiografie e documenti medici possono contenere dati sanitari sensibili e sono trattati per valutare la richiesta."], ["Statistiche", "Google Analytics è disattivato per impostazione predefinita e viene caricato solo dopo il consenso."], ["I tuoi diritti", "Per accesso, rettifica o cancellazione dei dati, scrivi a virtusdentalpro@gmail.com."]]],
    cookies: ["Cookie", "Il sito limita l'uso di cookie e tecnologie di tracciamento.", [["Cookie necessari", "Servono al funzionamento tecnico, alla navigazione e ad alcune preferenze."], ["Statistiche facoltative", "Google Analytics viene caricato solo dopo il consenso e la scelta viene salvata nel browser."], ["Servizi esterni", "Mappe, tour virtuali e social possono caricare contenuti di terze parti quando vengono aperti."]]],
    legal: ["Note legali", "Informazioni generali sul sito Virtus Dental Center.", [["Editore", "Virtus Dental Center, Rruga Teodor Keko, Pll 29, 1027 Tirana, Albania. Email: virtusdentalpro@gmail.com. Tel.: +33 6 28 27 01 18."], ["Informazioni", "I contenuti sono informativi e non costituiscono diagnosi, prescrizione o garanzia di risultato. Le indicazioni devono essere confermate dopo una visita clinica."], ["Diritti sui contenuti", "Testi, foto, video, grafiche e marchi sono protetti dalle norme applicabili. È vietato il riutilizzo non autorizzato."], ["Emergenza", "In caso di difficoltà respiratoria o di deglutizione, forte gonfiore del viso o del collo o altra situazione di pericolo, contatta immediatamente i servizi di emergenza locali."]]]
  },
  es: {
    privacy: ["Política de privacidad", "Información sobre los datos enviados a través del sitio de Virtus Dental Center.", [["Datos proporcionados", "El formulario recibe la información que eliges enviar, como nombre, país, email, teléfono, mensaje y archivos, para responder a tu solicitud."], ["Datos de salud", "Envía solo la información necesaria. Las fotos, radiografías y documentos médicos pueden contener datos sensibles y se utilizan para valorar la solicitud."], ["Estadísticas", "Google Analytics está desactivado por defecto y solo se carga después de tu consentimiento."], ["Tus derechos", "Para solicitar acceso, corrección o eliminación, escribe a virtusdentalpro@gmail.com."]]],
    cookies: ["Política de cookies", "El sitio limita el uso de cookies y tecnologías de seguimiento.", [["Cookies necesarias", "Permiten el funcionamiento técnico, la navegación y determinadas preferencias."], ["Estadísticas opcionales", "Google Analytics solo se carga después del consentimiento y la elección se guarda en el navegador."], ["Servicios externos", "Mapas, visitas virtuales y redes sociales pueden cargar contenido de terceros cuando se abren."]]],
    legal: ["Aviso legal", "Información general sobre el sitio de Virtus Dental Center.", [["Editor", "Virtus Dental Center, Rruga Teodor Keko, Pll 29, 1027 Tirana, Albania. Email: virtusdentalpro@gmail.com. Tel.: +33 6 28 27 01 18."], ["Naturaleza de la información", "El contenido es informativo y no constituye diagnóstico, receta ni garantía de resultado. Las indicaciones deben confirmarse tras un examen clínico."], ["Derechos de contenido", "Textos, fotos, vídeos, gráficos y marcas están protegidos por la normativa aplicable. Se prohíbe su reutilización no autorizada."], ["Urgencia", "Si tienes dificultad para respirar o tragar, hinchazón importante de cara o cuello u otra situación de riesgo inmediato, contacta con los servicios de emergencia locales."]]]
  },
  de: {
    privacy: ["Datenschutzerklärung", "Informationen über Daten, die über die Website von Virtus Dental Center übermittelt werden.", [["Bereitgestellte Daten", "Das Formular erhält die von Ihnen freiwillig übermittelten Angaben wie Name, Land, E-Mail, Telefon, Nachricht und Anhänge zur Bearbeitung Ihrer Anfrage."], ["Gesundheitsdaten", "Übermitteln Sie nur notwendige Informationen. Fotos, Röntgenbilder und medizinische Dokumente können sensible Gesundheitsdaten enthalten."], ["Statistik", "Google Analytics ist standardmäßig deaktiviert und wird erst nach Ihrer Zustimmung geladen."], ["Ihre Rechte", "Für Auskunft, Berichtigung oder Löschung kontaktieren Sie virtusdentalpro@gmail.com."]]],
    cookies: ["Cookie-Richtlinie", "Die Website verwendet möglichst wenige Cookies und Tracking-Technologien.", [["Notwendige Cookies", "Sie unterstützen den technischen Betrieb, die Navigation und bestimmte Einstellungen."], ["Optionale Statistik", "Google Analytics wird erst nach Zustimmung geladen; die Auswahl wird im Browser gespeichert."], ["Externe Dienste", "Karten, virtuelle Rundgänge und soziale Netzwerke können beim Öffnen Inhalte von Drittanbietern laden."]]],
    legal: ["Impressum", "Allgemeine Informationen zur Website des Virtus Dental Center.", [["Anbieter", "Virtus Dental Center, Rruga Teodor Keko, Pll 29, 1027 Tirana, Albanien. E-Mail: virtusdentalpro@gmail.com. Tel.: +33 6 28 27 01 18."], ["Art der Informationen", "Die Inhalte dienen der Information und sind keine Diagnose, Verordnung oder Ergebnisgarantie. Behandlungsindikationen müssen klinisch bestätigt werden."], ["Inhaltsrechte", "Texte, Fotos, Videos, Grafiken und Marken sind geschützt. Unbefugte Nutzung ist untersagt."], ["Notfall", "Bei Atem- oder Schluckproblemen, starker Schwellung von Gesicht oder Hals oder einer anderen akuten Gefahr wenden Sie sich sofort an den örtlichen Notdienst."]]]
  },
  pt: {
    privacy: ["Política de privacidade", "Informações sobre os dados enviados através do site da Virtus Dental Center.", [["Dados fornecidos", "O formulário recebe os dados que escolhe enviar, como nome, país, email, telefone, mensagem e anexos, para responder ao pedido."], ["Dados de saúde", "Envie apenas o necessário. Fotografias, radiografias e documentos médicos podem conter dados de saúde sensíveis."], ["Estatísticas", "O Google Analytics fica desativado por defeito e só é carregado após o seu consentimento."], ["Os seus direitos", "Para acesso, correção ou eliminação, contacte virtusdentalpro@gmail.com."]]],
    cookies: ["Política de cookies", "O site procura limitar cookies e tecnologias de rastreio.", [["Cookies necessários", "Permitem o funcionamento técnico, a navegação e algumas preferências."], ["Estatísticas opcionais", "O Google Analytics só é carregado após consentimento e a escolha fica guardada no navegador."], ["Serviços externos", "Mapas, visitas virtuais e redes sociais podem carregar conteúdo de terceiros quando são abertos."]]],
    legal: ["Aviso legal", "Informações gerais sobre o site da Virtus Dental Center.", [["Editor", "Virtus Dental Center, Rruga Teodor Keko, Pll 29, 1027 Tirana, Albânia. Email: virtusdentalpro@gmail.com. Tel.: +33 6 28 27 01 18."], ["Natureza da informação", "O conteúdo é informativo e não constitui diagnóstico, prescrição ou garantia de resultado. As indicações devem ser confirmadas após avaliação clínica."], ["Direitos de conteúdo", "Textos, fotografias, vídeos, gráficos e marcas são protegidos. A reutilização não autorizada é proibida."], ["Emergência", "Em caso de dificuldade para respirar ou engolir, inchaço importante da face ou pescoço ou outra situação de risco, contacte imediatamente os serviços de emergência locais."]]]
  },
  ru: {
    privacy: ["Политика конфиденциальности", "Информация о данных, передаваемых через сайт Virtus Dental Center.", [["Предоставленные данные", "Форма получает только сведения, которые вы отправляете добровольно: имя, страна, email, телефон, сообщение и вложения, чтобы ответить на запрос."], ["Медицинские данные", "Отправляйте только необходимую информацию. Фото, рентгеновские снимки и медицинские документы могут содержать чувствительные данные."], ["Статистика", "Google Analytics отключён по умолчанию и загружается только после вашего согласия."], ["Ваши права", "Для доступа, исправления или удаления данных напишите на virtusdentalpro@gmail.com."]]],
    cookies: ["Политика cookies", "Сайт стремится использовать минимум cookies и технологий отслеживания.", [["Необходимые cookies", "Они поддерживают работу сайта, навигацию и отдельные настройки."], ["Необязательная статистика", "Google Analytics загружается только после согласия, а выбор сохраняется в браузере."], ["Внешние сервисы", "Карты, виртуальные туры и социальные сети могут загружать сторонний контент при открытии."]]],
    legal: ["Правовая информация", "Общая информация о сайте Virtus Dental Center.", [["Издатель", "Virtus Dental Center, Rruga Teodor Keko, Pll 29, 1027 Tirana, Albania. Email: virtusdentalpro@gmail.com. Тел.: +33 6 28 27 01 18."], ["Характер информации", "Материалы носят информационный характер и не являются диагнозом, назначением или гарантией результата. Показания подтверждаются после клинического осмотра."], ["Права на контент", "Тексты, фотографии, видео, графика и товарные знаки защищены применимым законодательством. Несанкционированное использование запрещено."], ["Экстренная помощь", "При затруднении дыхания или глотания, значительном отёке лица или шеи либо другой непосредственной опасности немедленно обращайтесь в местные экстренные службы."]]]
  },
  ar: {
    privacy: ["سياسة الخصوصية", "معلومات حول البيانات التي يتم إرسالها عبر موقع Virtus Dental Center.", [["البيانات التي تقدمها", "يستقبل النموذج المعلومات التي تختار إرسالها مثل الاسم والبلد والبريد والهاتف والرسالة والمرفقات للرد على طلبك."], ["البيانات الصحية", "أرسل المعلومات الضرورية فقط. قد تحتوي الصور والأشعة والوثائق الطبية على بيانات صحية حساسة وتستخدم لتقييم الطلب."], ["الإحصاءات", "Google Analytics معطل افتراضيًا ولا يتم تحميله إلا بعد موافقتك."], ["حقوقك", "لطلب الوصول أو التصحيح أو الحذف، تواصل عبر virtusdentalpro@gmail.com."]]],
    cookies: ["سياسة ملفات الارتباط", "يهدف الموقع إلى استخدام الحد الأدنى من ملفات الارتباط وتقنيات التتبع.", [["الملفات الضرورية", "تدعم التشغيل التقني والتنقل وبعض التفضيلات."], ["الإحصاءات الاختيارية", "يتم تحميل Google Analytics بعد الموافقة فقط، ويتم حفظ الاختيار في المتصفح."], ["الخدمات الخارجية", "قد تقوم الخرائط والجولات الافتراضية والشبكات الاجتماعية بتحميل محتوى من جهات خارجية عند فتحها."]]],
    legal: ["معلومات قانونية", "معلومات عامة حول موقع Virtus Dental Center.", [["الناشر", "Virtus Dental Center، Rruga Teodor Keko, Pll 29, 1027 Tirana, Albania. البريد: virtusdentalpro@gmail.com. الهاتف: +33 6 28 27 01 18."], ["طبيعة المعلومات", "المحتوى معلوماتي ولا يشكل تشخيصًا أو وصفة أو ضمانًا للنتيجة. يجب تأكيد أي خطة علاج بعد الفحص السريري."], ["حقوق المحتوى", "النصوص والصور والفيديو والرسومات والعلامات محمية بالقوانين المعمول بها. يمنع إعادة الاستخدام غير المصرح به."], ["الطوارئ", "عند صعوبة التنفس أو البلع، أو تورم شديد في الوجه أو الرقبة، أو أي خطر فوري، اتصل بخدمات الطوارئ المحلية فورًا."]]]
  },
  sq: {
    privacy: ["Politika e privatësisë", "Informacion mbi të dhënat e dërguara përmes faqes së Virtus Dental Center.", [["Të dhënat e dhëna", "Formulari merr vetëm informacionin që zgjidhni të dërgoni, si emri, shteti, emaili, telefoni, mesazhi dhe bashkëngjitjet, për t'iu përgjigjur kërkesës."], ["Të dhënat shëndetësore", "Dërgoni vetëm informacionin e nevojshëm. Fotot, radiografitë dhe dokumentet mjekësore mund të përmbajnë të dhëna të ndjeshme."], ["Statistikat", "Google Analytics është i çaktivizuar si parazgjedhje dhe ngarkohet vetëm pas pëlqimit tuaj."], ["Të drejtat tuaja", "Për akses, korrigjim ose fshirje, kontaktoni virtusdentalpro@gmail.com."]]],
    cookies: ["Politika e cookies", "Faqja synon të përdorë sa më pak cookies dhe teknologji gjurmimi.", [["Cookies të nevojshme", "Mbështesin funksionimin teknik, navigimin dhe disa preferenca."], ["Statistika opsionale", "Google Analytics ngarkohet vetëm pas pëlqimit dhe zgjedhja ruhet në shfletues."], ["Shërbime të jashtme", "Hartat, turet virtuale dhe rrjetet sociale mund të ngarkojnë përmbajtje të palëve të treta kur hapen."]]],
    legal: ["Njoftim ligjor", "Informacion i përgjithshëm për faqen e Virtus Dental Center.", [["Publikuesi", "Virtus Dental Center, Rruga Teodor Keko, Pll 29, 1027 Tiranë, Shqipëri. Email: virtusdentalpro@gmail.com. Tel.: +33 6 28 27 01 18."], ["Natyra e informacionit", "Përmbajtja është informuese dhe nuk përbën diagnozë, recetë ose garanci rezultati. Indikacionet duhet të konfirmohen pas ekzaminimit klinik."], ["Të drejtat e përmbajtjes", "Tekstet, fotot, videot, grafikat dhe markat mbrohen nga ligji. Ripërdorimi pa autorizim ndalohet."], ["Urgjenca", "Nëse keni vështirësi në frymëmarrje ose gëlltitje, ënjtje të madhe të fytyrës/qafës ose rrezik të menjëhershëm, kontaktoni urgjencën lokale."]]]
  },
  zh: {
    privacy: ["隐私政策", "关于通过 Virtus Dental Center 网站提交的数据的信息。", [["您主动提供的数据", "表单会接收您主动提交的姓名、国家、邮箱、电话、留言和附件，用于回复您的请求。"], ["健康数据", "请仅发送必要的信息。照片、X光片和医疗文件可能包含敏感健康数据，用于评估您的请求。"], ["统计", "Google Analytics 默认关闭，只有在您同意后才会加载。"], ["您的权利", "如需访问、更正或删除信息，请联系 virtusdentalpro@gmail.com。"]]],
    cookies: ["Cookie 政策", "本网站尽量减少 Cookie 和跟踪技术的使用。", [["必要 Cookie", "用于网站技术运行、导航和部分偏好设置。"], ["可选统计", "Google Analytics 只有在您同意后才会加载，选择会保存在浏览器中。"], ["外部服务", "地图、虚拟参观和社交网络打开时可能加载第三方内容。"]]],
    legal: ["法律声明", "Virtus Dental Center 网站的一般信息。", [["网站运营方", "Virtus Dental Center，Rruga Teodor Keko, Pll 29, 1027 Tirana, Albania。邮箱：virtusdentalpro@gmail.com。电话：+33 6 28 27 01 18。"], ["信息性质", "网站内容仅供参考，不构成诊断、处方或治疗结果保证。治疗方案必须在临床检查后确认。"], ["内容权利", "文字、照片、视频、图形和商标受适用法律保护，未经授权不得重复使用。"], ["紧急情况", "如出现呼吸或吞咽困难、明显的面部或颈部肿胀，或其他即时安全风险，请立即联系当地急救服务。"]]]
  }
};

const COMMON = { fr:["Accueil","Confidentialité","Cookies","Mentions légales"], en:["Home","Privacy","Cookies","Legal notice"], it:["Home","Privacy","Cookie","Note legali"], es:["Inicio","Privacidad","Cookies","Aviso legal"], de:["Start","Datenschutz","Cookies","Impressum"], pt:["Início","Privacidade","Cookies","Aviso legal"], ru:["Главная","Конфиденциальность","Cookies","Правовая информация"], ar:["الرئيسية","الخصوصية","ملفات الارتباط","معلومات قانونية"], sq:["Kryesore","Privatësia","Cookies","Njoftim ligjor"], zh:["首页","隐私政策","Cookie 政策","法律声明"]};

export default function LegalPage({ type }) {
  const { lang } = useLanguage();
  const { page } = useParams();
  const selected = type || page || "privacy";
  const data = (BASE[lang] || BASE.en)[selected] || BASE.en.privacy;
  const common = COMMON[lang] || COMMON.en;
  const prefix = lang === "fr" ? "" : `/${lang}`;
  return <><SEOHead page={{ type: "page", title: data[0], description: data[1], slug: selected }} /><Header /><main className="legal-page"><section className="info-hero"><div className="wrap"><p className="breadcrumb"><Link to={prefix || "/"}>{common[0]}</Link> <span>/</span> {data[0]}</p><span className="sample-tag">VIRTUS · INFORMATION</span><h1>{data[0]}</h1><p>{data[1]}</p></div></section><section className="info-content"><div className="wrap"><div className="info-sections">{data[2].map(([title, body]) => <article key={title}><h2>{title}</h2><p>{body}</p></article>)}</div></div></section></main><Footer /></>;
}
