import { useLanguage } from "../context/LanguageContext";
import SmartAnchor from "./SmartAnchor";
import { useReveal } from "../hooks/useReveal";

const COPY={
fr:{eyebrow:"TARIFS INDICATIFS",title:"Une première idée du budget",intro:"Les tarifs ci-dessous reprennent des montants publiquement affichés sur les pages Virtus consultées. Le devis final dépend du bilan, des matériaux et de la complexité du cas.",rows:[["Implant dentaire unitaire","400–800 €","Selon le système et la restauration"],["All-on-4 · céramique","à partir de 6 000 €","Arche complète · tarif publié"],["All-on-4 · zircone","à partir de 7 440 €","Arche complète · tarif publié"],["All-on-6 / All-on-8","5 000–8 000 €","Fourchette indicative publiée"],["Couronne céramique / zircone","150–300 € / dent","Selon le matériau"],["Autres traitements","Sur devis","Après évaluation clinique"]],note:"Tarifs indicatifs, non contractuels. Demandez un devis écrit détaillant le traitement, les matériaux et ce qui est inclus avant de réserver le voyage.",cta:"Demander mon devis"},
en:{eyebrow:"INDICATIVE PRICING",title:"A clear first budget reference",intro:"These figures reproduce amounts publicly displayed on the Virtus pages reviewed. The final quote depends on the clinical assessment, materials and complexity of the case.",rows:[["Single dental implant","€400–800","Depending on system and restoration"],["All-on-4 · ceramic","from €6,000","Full arch · published figure"],["All-on-4 · zirconia","from €7,440","Full arch · published figure"],["All-on-6 / All-on-8","€5,000–8,000","Published indicative range"],["Ceramic / zirconia crown","€150–300 / tooth","Depending on material"],["Other treatments","Quote","After clinical assessment"]],note:"Indicative, non-contractual prices. Ask for a written quote detailing treatment, materials and inclusions before booking travel.",cta:"Request my quote"}
};
const GENERIC={it:{eyebrow:"PREZZI INDICATIVI",title:"Un primo riferimento di budget",intro:"I valori indicati riprendono importi pubblicati da Virtus. Il preventivo finale dipende dalla valutazione clinica.",cta:"Richiedi un preventivo"},es:{eyebrow:"PRECIOS ORIENTATIVOS",title:"Una primera referencia de presupuesto",intro:"Los importes retoman cifras publicadas por Virtus. El presupuesto final depende de la evaluación clínica.",cta:"Solicitar presupuesto"},de:{eyebrow:"RICHTPREISE",title:"Eine erste Budgetorientierung",intro:"Die Werte beziehen sich auf öffentlich angegebene Virtus-Preise. Das endgültige Angebot hängt von der klinischen Untersuchung ab.",cta:"Angebot anfragen"},pt:{eyebrow:"PREÇOS INDICATIVOS",title:"Uma primeira referência de orçamento",intro:"Os valores retomam montantes publicados pela Virtus. O orçamento final depende da avaliação clínica.",cta:"Pedir orçamento"},ru:{eyebrow:"ОРИЕНТИРОВОЧНЫЕ ЦЕНЫ",title:"Первый ориентир по бюджету",intro:"Суммы основаны на опубликованных Virtus значениях. Итоговая смета зависит от клинической оценки.",cta:"Запросить расчёт"},ar:{eyebrow:"أسعار إرشادية",title:"مرجع أولي للميزانية",intro:"تستند القيم إلى أسعار منشورة من Virtus. السعر النهائي يعتمد على التقييم السريري.",cta:"اطلب عرض سعر"},sq:{eyebrow:"ÇMIME ORIENTUESE",title:"Një ide e parë për buxhetin",intro:"Vlerat bazohen në shifra të publikuara nga Virtus. Oferta përfundimtare varet nga vlerësimi klinik.",cta:"Kërko ofertë"},zh:{eyebrow:"参考价格",title:"先了解一个预算范围",intro:"以下数字来自 Virtus 公开页面。最终报价取决于临床评估、材料和病例复杂程度。",cta:"申请报价"}};
export default function Pricing(){const {lang,content}=useLanguage();const ref=useReveal();const d={...(COPY[lang]||COPY.en),...(GENERIC[lang]||{})};return <section className="pricing-section reveal" ref={ref} id="pricing"><div className="wrap"><div className="pricing-head"><div className="sec-head"><span className="eyebrow">{d.eyebrow}</span><h2>{d.title}</h2><p>{d.intro}</p></div><SmartAnchor href="#contact" className="btn btn-primary">{d.cta} <span>↗</span></SmartAnchor></div><div className="pricing-table-wrap"><table className="pricing-table"><thead><tr><th>{lang==="fr"?"Traitement":lang==="it"?"Trattamento":lang==="es"?"Tratamiento":lang==="de"?"Behandlung":lang==="pt"?"Tratamento":lang==="ru"?"Лечение":lang==="ar"?"العلاج":lang==="sq"?"Trajtimi":lang==="zh"?"治疗":"Treatment"}</th><th>{lang==="fr"?"Prix indicatif":lang==="it"?"Prezzo indicativo":lang==="es"?"Precio orientativo":lang==="de"?"Richtpreis":lang==="pt"?"Preço indicativo":lang==="ru"?"Ориентир":lang==="ar"?"السعر الإرشادي":lang==="sq"?"Çmim orientues":lang==="zh"?"参考价格":"Indicative price"}</th><th>{lang==="fr"?"Détail":lang==="it"?"Dettagli":lang==="es"?"Detalle":lang==="de"?"Details":lang==="pt"?"Detalhes":lang==="ru"?"Детали":lang==="ar"?"التفاصيل":lang==="sq"?"Detaje":lang==="zh"?"说明":"Details"}</th></tr></thead><tbody>{d.rows.map((r,i)=><tr key={i}><td>{r[0]}</td><td className="price-strong">{r[1]}</td><td>{r[2]}</td></tr>)}</tbody></table></div><div className="pricing-note"><strong>ⓘ</strong><span>{d.note}</span></div></div></section>}
