import { useEffect, useMemo, useState } from "react";
import { useLanguage } from "../context/LanguageContext";
import { useReveal } from "../hooks/useReveal";

const COPY={
fr:{eyebrow:"SMILE LAB",title:"Attrapez le sourire",intro:"30 secondes. La dent cible bouge, le compteur monte. Voyons votre réflexe.",start:"Lancer le défi",restart:"Rejouer",score:"Score",combo:"Combo",time:"Temps",ready:"Prêt ?",done:"Défi terminé",best:"Objectif : 15 points",hint:"Jeu purement ludique — aucun conseil médical n’est donné par le jeu."},
en:{eyebrow:"SMILE LAB",title:"Catch the smile",intro:"30 seconds. The target tooth moves and your score climbs. Test your reflexes.",start:"Start challenge",restart:"Play again",score:"Score",combo:"Combo",time:"Time",ready:"Ready?",done:"Challenge complete",best:"Target: 15 points",hint:"Just for fun — the game does not provide medical advice."},
it:{eyebrow:"SMILE LAB",title:"Cattura il sorriso",intro:"30 secondi. Il dente obiettivo si muove: prova i tuoi riflessi.",start:"Inizia",restart:"Gioca ancora",score:"Punti",combo:"Combo",time:"Tempo",ready:"Pronto?",done:"Sfida completata",best:"Obiettivo: 15 punti",hint:"Solo per divertimento — il gioco non fornisce consigli medici."},
es:{eyebrow:"SMILE LAB",title:"Atrapa la sonrisa",intro:"30 segundos. El diente objetivo se mueve. Pon a prueba tus reflejos.",start:"Empezar",restart:"Jugar de nuevo",score:"Puntos",combo:"Combo",time:"Tiempo",ready:"¿Listo?",done:"Reto terminado",best:"Objetivo: 15 puntos",hint:"Solo por diversión — el juego no da consejos médicos."},
de:{eyebrow:"SMILE LAB",title:"Fangen Sie das Lächeln",intro:"30 Sekunden. Der Zielzahn bewegt sich. Testen Sie Ihre Reaktion.",start:"Starten",restart:"Noch einmal",score:"Punkte",combo:"Combo",time:"Zeit",ready:"Bereit?",done:"Challenge beendet",best:"Ziel: 15 Punkte",hint:"Nur zum Spaß — das Spiel gibt keine medizinischen Ratschläge."},
pt:{eyebrow:"SMILE LAB",title:"Apanhe o sorriso",intro:"30 segundos. O dente-alvo muda de posição. Teste os seus reflexos.",start:"Começar",restart:"Jogar novamente",score:"Pontos",combo:"Combo",time:"Tempo",ready:"Pronto?",done:"Desafio terminado",best:"Objetivo: 15 pontos",hint:"Apenas por diversão — o jogo não fornece conselhos médicos."},
ru:{eyebrow:"SMILE LAB",title:"Поймайте улыбку",intro:"30 секунд. Целевой зуб перемещается — проверьте реакцию.",start:"Начать",restart:"Сыграть снова",score:"Очки",combo:"Комбо",time:"Время",ready:"Готовы?",done:"Испытание завершено",best:"Цель: 15 очков",hint:"Только для развлечения — игра не даёт медицинских советов."},
ar:{eyebrow:"SMILE LAB",title:"التقط الابتسامة",intro:"30 ثانية. السن المستهدف يتحرك. اختبر سرعة استجابتك.",start:"ابدأ التحدي",restart:"العب مرة أخرى",score:"النقاط",combo:"السلسلة",time:"الوقت",ready:"جاهز؟",done:"انتهى التحدي",best:"الهدف: 15 نقطة",hint:"للترفيه فقط — اللعبة لا تقدم نصائح طبية."},
sq:{eyebrow:"SMILE LAB",title:"Kapni buzëqeshjen",intro:"30 sekonda. Dhëmbi objektiv lëviz. Provoni refleksin tuaj.",start:"Fillo",restart:"Luaj përsëri",score:"Pikë",combo:"Combo",time:"Koha",ready:"Gati?",done:"Sfida përfundoi",best:"Objektivi: 15 pikë",hint:"Vetëm për argëtim — loja nuk jep këshilla mjekësore."},
zh:{eyebrow:"SMILE LAB",title:"抓住笑容",intro:"30 秒挑战。目标牙齿会移动，测试一下你的反应速度。",start:"开始挑战",restart:"再玩一次",score:"得分",combo:"连击",time:"时间",ready:"准备好了吗？",done:"挑战完成",best:"目标：15 分",hint:"仅供娱乐——游戏不提供医疗建议。"}
};
function Tooth(){return <svg viewBox="0 0 48 56" aria-hidden="true"><path d="M14 4c-6 1-9 6-8 13 .7 5 4 8 5 14 1 7 2 17 7 17 4 0 4-7 6-13 1-5 2-5 4 0 2 6 2 13 6 13 5 0 6-10 7-17 1-6 4-9 5-14C47 10 44 5 38 4c-5-1-8 2-11 2s-8-3-13-2Z" fill="currentColor"/></svg>}
export default function SmileChallenge(){const {lang}=useLanguage();const ref=useReveal();const d=COPY[lang]||COPY.en;const positions=useMemo(()=>Array.from({length:9},(_,i)=>({left:`${8+(i%3)*35}%`,top:`${12+Math.floor(i/3)*35}%`})),[]);const [running,setRunning]=useState(false),[time,setTime]=useState(30),[score,setScore]=useState(0),[combo,setCombo]=useState(0),[target,setTarget]=useState(4),[hits,setHits]=useState(0);useEffect(()=>{if(!running)return;const t=setInterval(()=>setTime(v=>v<=1?0:v-1),1000);return()=>clearInterval(t)},[running]);useEffect(()=>{if(running&&time===0)setRunning(false)},[running,time]);useEffect(()=>{if(!running)return;const mover=setInterval(()=>setTarget(Math.floor(Math.random()*positions.length)),1100);return()=>clearInterval(mover)},[running,positions.length]);const start=()=>{setTime(30);setScore(0);setCombo(0);setHits(0);setTarget(Math.floor(Math.random()*positions.length));setRunning(true)};const hit=(i)=>{if(!running)return;if(i===target){setScore(v=>v+1+Math.min(combo,4));setCombo(v=>v+1);setHits(v=>v+1);setTarget(Math.floor(Math.random()*positions.length))}else setCombo(0)};return <section className="smile-challenge reveal" ref={ref} id="smile-challenge"><div className="wrap"><div className="game-shell game-shell-pro"><div className="game-copy"><span className="eyebrow">{d.eyebrow}</span><h2>{d.title}</h2><p>{d.intro}</p><div className="game-stats"><span><b>{score}</b> {d.score}</span><span><b>x{combo}</b> {d.combo}</span><span><b>{time}s</b> {d.time}</span></div><div className="game-progress"><i style={{width:`${(time/30)*100}%`}}/></div><button className="btn btn-primary" onClick={start}>{running?d.restart:(time===0?d.restart:d.start)} <span>↗</span></button><div className="game-goal">{d.best}</div><small>{d.hint}</small></div><div className="game-board game-board-pro">{!running&&<div className="game-overlay"><strong>{time===0?d.done:d.ready}</strong>{time===0&&<span>{score} {d.score}</span>}<em>🦷</em></div>}{positions.map((pos,i)=><button key={i} className={`game-tooth game-tooth-pro${i===target&&running?" target":""}`} style={pos} onClick={()=>hit(i)} aria-label={`${d.score} ${i+1}`}><Tooth/></button>)}<div className="game-counter">{hits} ✓</div></div></div></div></section>}
