import { Link } from "react-router-dom";
import { useLanguage } from "../context/LanguageContext";
import { useReveal } from "../hooks/useReveal";

const COPY = {
  fr: { eyebrow:"CENTRE DE CONFIANCE", title:"Avant de choisir une clinique à l’étranger, vérifiez les bonnes choses.", intro:"Nous préférons montrer le parcours et les éléments que vous pouvez contrôler plutôt que multiplier les promesses.", items:[["Équipe identifiable","Consultez les profils, spécialités et photos des membres de l’équipe Virtus."],["Clinique visible","Explorez la visite virtuelle et les espaces avant votre déplacement."],["Cas présentés avec prudence","Les photos avant/après illustrent des situations réelles ; elles ne garantissent jamais un résultat identique."],["Devis personnalisé","Le prix final dépend de l’examen et du plan de traitement, pas d’un simple formulaire en ligne."],["Dossier préparé avant le départ","Photos, radios et informations médicales disponibles peuvent accélérer la première analyse."],["Suivi après le retour","Les modalités de contrôle et de suivi sont expliquées avant le traitement."]], cta:"Voir notre parcours patient" },
  en: { eyebrow:"TRUST CENTER", title:"Before choosing a clinic abroad, check the things that matter.", intro:"We prefer to show the pathway and the evidence you can review rather than add more marketing promises.", items:[["Identifiable team","Review the profiles, specialties and photos of the Virtus team."],["Clinic you can see","Explore the virtual tour and clinic spaces before travelling."],["Cases presented carefully","Before-and-after images illustrate cases; they never guarantee an identical outcome."],["Personalised quote","Final pricing depends on assessment and treatment planning, not on an online form alone."],["Records prepared before travel","Photos, X-rays and available medical information can help the initial review."],["Follow-up after you return","Follow-up and review arrangements are explained before treatment."]], cta:"See the patient journey" },
  it: { eyebrow:"CENTRO FIDUCIA", title:"Prima di scegliere una clinica all’estero, verifica ciò che conta.", intro:"Preferiamo mostrare il percorso e gli elementi che puoi controllare invece di aggiungere promesse pubblicitarie.", items:[["Team identificabile","Consulta profili, specialità e foto del team Virtus."],["Clinica visibile","Esplora il tour virtuale prima del viaggio."],["Casi presentati con prudenza","Le immagini prima/dopo illustrano casi e non garantiscono lo stesso risultato."],["Preventivo personalizzato","Il prezzo finale dipende dalla valutazione clinica e dal piano di trattamento."],["Documenti pronti","Foto, radiografie e informazioni disponibili aiutano la prima analisi."],["Follow-up","Le modalità di controllo dopo il trattamento vengono spiegate prima della cura."]], cta:"Vedi il percorso paziente" },
  es: { eyebrow:"CENTRO DE CONFIANZA", title:"Antes de elegir una clínica en el extranjero, comprueba lo importante.", intro:"Preferimos mostrar el proceso y los elementos que puedes revisar antes que añadir promesas de marketing.", items:[["Equipo identificable","Consulta perfiles, especialidades y fotos del equipo Virtus."],["Clínica visible","Explora la visita virtual antes de viajar."],["Casos presentados con prudencia","Las imágenes antes/después ilustran casos y no garantizan el mismo resultado."],["Presupuesto personalizado","El precio final depende de la valoración y del plan de tratamiento."],["Documentación preparada","Fotos, radiografías e información disponible ayudan a la primera revisión."],["Seguimiento","Las revisiones y el seguimiento se explican antes del tratamiento."]], cta:"Ver el recorrido del paciente" },
  de: { eyebrow:"VERTRAUEN", title:"Bevor Sie eine Klinik im Ausland wählen, prüfen Sie die wichtigen Punkte.", intro:"Wir zeigen lieber den Ablauf und überprüfbare Informationen, statt zusätzliche Marketingversprechen zu machen.", items:[["Identifizierbares Team","Profile, Fachgebiete und Fotos des Virtus-Teams ansehen."],["Sichtbare Klinik","Virtuelle Tour vor der Reise ansehen."],["Vorsichtig dargestellte Fälle","Vorher-Nachher-Bilder zeigen Fälle und garantieren kein identisches Ergebnis."],["Individueller Kostenvoranschlag","Der Endpreis hängt von Untersuchung und Behandlungsplan ab."],["Unterlagen vorbereiten","Fotos, Röntgenbilder und vorhandene Informationen helfen bei der ersten Einschätzung."],["Nachsorge","Kontrollen und Nachsorge werden vor der Behandlung erklärt."]], cta:"Patientenweg ansehen" },
  pt: { eyebrow:"CENTRO DE CONFIANÇA", title:"Antes de escolher uma clínica no estrangeiro, verifique o que importa.", intro:"Preferimos mostrar o percurso e os elementos que pode analisar em vez de acrescentar promessas de marketing.", items:[["Equipa identificável","Consulte perfis, especialidades e fotografias da equipa Virtus."],["Clínica visível","Explore a visita virtual antes da viagem."],["Casos apresentados com cuidado","As imagens antes/depois ilustram casos e não garantem o mesmo resultado."],["Orçamento personalizado","O preço final depende da avaliação e do plano de tratamento."],["Documentos preparados","Fotografias, radiografias e informação disponível ajudam na análise inicial."],["Acompanhamento","As revisões e o acompanhamento são explicados antes do tratamento."]], cta:"Ver percurso do paciente" },
  ru: { eyebrow:"ЦЕНТР ДОВЕРИЯ", title:"Перед выбором клиники за рубежом проверьте главное.", intro:"Мы предпочитаем показывать процесс и проверяемые сведения, а не добавлять рекламные обещания.", items:[["Понятная команда","Изучите профили, специализации и фотографии команды Virtus."],["Клинику можно увидеть","Посмотрите виртуальный тур до поездки."],["Случаи представлены осторожно","Фото до/после иллюстрируют случаи и не гарантируют одинаковый результат."],["Персональный план и смета","Итоговая стоимость зависит от обследования и плана лечения."],["Подготовка документов","Фото, снимки и доступная медицинская информация помогают первичной оценке."],["Наблюдение после возвращения","Порядок контроля и наблюдения объясняется до лечения."]], cta:"Посмотреть путь пациента" },
  ar: { eyebrow:"مركز الثقة", title:"قبل اختيار عيادة في الخارج، تحقّق من الأمور المهمة.", intro:"نفضّل عرض المسار والمعلومات التي يمكنك مراجعتها بدلاً من إضافة وعود تسويقية.", items:[["فريق واضح الهوية","اطّلع على ملفات أعضاء فريق Virtus وتخصصاتهم وصورهم."],["عيادة يمكنك رؤيتها","استكشف الجولة الافتراضية قبل السفر."],["حالات معروضة بحذر","صور قبل/بعد توضح حالات ولا تضمن نتيجة مطابقة."],["عرض شخصي","التكلفة النهائية تعتمد على التقييم وخطة العلاج."],["تجهيز الملف","الصور والأشعة والمعلومات المتاحة تساعد في التقييم الأولي."],["المتابعة","يتم شرح الفحوصات والمتابعة قبل العلاج."]], cta:"شاهد رحلة المريض" },
  sq: { eyebrow:"QENDRA E BESIMIT", title:"Para se të zgjidhni një klinikë jashtë vendit, kontrolloni gjërat që kanë rëndësi.", intro:"Ne preferojmë të tregojmë procesin dhe informacionin që mund të kontrolloni, jo të shtojmë premtime marketingu.", items:[["Ekip i identifikueshëm","Shikoni profilet, specialitetet dhe fotot e ekipit Virtus."],["Klinikë e vizitueshme","Eksploroni turin virtual para udhëtimit."],["Raste të paraqitura me kujdes","Fotot para/pas ilustrojnë raste dhe nuk garantojnë të njëjtin rezultat."],["Preventiv personal","Çmimi përfundimtar varet nga vlerësimi dhe plani i trajtimit."],["Dokumentet gati","Fotot, radiografitë dhe informacionet e disponueshme ndihmojnë analizën fillestare."],["Ndjekje pas kthimit","Kontrollet dhe ndjekja shpjegohen para trajtimit."]], cta:"Shihni rrugëtimin e pacientit" },
  zh: { eyebrow:"信任中心", title:"在选择海外牙科诊所前，先核实真正重要的信息。", intro:"我们更愿意展示可检查的流程和资料，而不是增加营销承诺。", items:[["团队信息清晰","查看 Virtus 团队成员的个人资料、专业领域和照片。"],["可以在线参观诊所","出行前先查看虚拟导览。"],["病例谨慎展示","治疗前后图片用于展示病例，不保证相同结果。"],["个性化报价","最终费用取决于检查结果和治疗计划。"],["提前准备资料","照片、X光片和现有医疗资料有助于初步评估。"],["回国后的随访","治疗前会说明复查和随访安排。" ]], cta:"查看患者流程" }
};

export default function TrustCenter(){
 const {lang}=useLanguage(); const ref=useReveal(); const c=COPY[lang]||COPY.en; const prefix=lang==="fr"?"":`/${lang}`;
 return <section className="trust-center reveal" ref={ref}><div className="wrap"><div className="section-head trust-head"><div><span className="eyebrow">{c.eyebrow}</span><h2>{c.title}</h2><p>{c.intro}</p></div></div><div className="trust-grid">{c.items.map(([t,d],i)=><article className="trust-card" key={t}><span className="trust-number">0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div><Link className="text-link trust-link" to={`${prefix}/dental-tourism`}>{c.cta} →</Link></div></section>
}
